### ISSUE TITLE
Custom value for fingerprint instead of timestamp

### ISSUE THREAD

**Issue by sann3** [burhanloey/cljs-simple-cache-buster#2]
Hi,

 By default the plugin can use the timestamp for {{ fingerprint }}. Is it possible to make the plugin to accept the custom value for {{ fingerprint }} ?

**Comment by sann3** [comment]
When we can expect the solution for this issue ?

**Comment by burhanloey** [comment]
If it is just supplying custom value manually, I can do it right away.

I'm planning to make like a custom generator or something.

I'll just implement manual solution for now.

**Comment by burhanloey** [comment]
Done.
